# Generated by Django 3.1.1 on 2020-09-04 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consulta', '0002_exame_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'Agendado'), ('E', 'Andamento'), ('C', 'Concluido')], max_length=1, null=True, verbose_name='Status')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.exame')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=100)),
                ('laudo', models.TextField(blank=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.consulta')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
            },
        ),
    ]
