# Generated by Django 3.1.1 on 2020-09-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_consulta_resultado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
    ]
