# Generated by Django 3.1.1 on 2020-09-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0004_auto_20200904_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
    ]
